export const WORDS = [
  'RIVIÈRE', 'COURANT', 'PONT', 'LUNE', 'SOLEIL', 'ÉTOILE', 'NUAGE', 'ORAGE', 'NEIGE', 'VOLCAN',
  'MONTAGNE', 'FORÊT', 'DÉSERT', 'OCÉAN', 'PLAGE', 'ÎLE', 'CHÂTEAU', 'TOUR', 'ÉGLISE', 'MARCHÉ',
  'BANQUE', 'PRISON', 'HÔPITAL', 'ÉCOLE', 'USINE', 'TRAIN', 'AVION', 'BATEAU', 'FUSÉE', 'VÉLO',
  'CLÉ', 'SERRURE', 'PORTE', 'FENÊTRE', 'MIROIR', 'HORLOGE', 'LAMPE', 'BOUGIE', 'CÂBLE', 'ANTENNE',
  'RADIO', 'ÉCRAN', 'CLAVIER', 'VIRUS', 'CODE', 'SIGNAL', 'RÉSEAU', 'SERVEUR', 'MÉMOIRE', 'FICHIER',
  'LION', 'SERPENT', 'AIGLE', 'REQUIN', 'ARAIGNÉE', 'LOUP', 'CHAT', 'BALEINE', 'ABEILLE', 'CORBEAU',
  'POMME', 'CITRON', 'PAIN', 'FROMAGE', 'CHOCOLAT', 'SEL', 'MIEL', 'CAFÉ', 'VIN', 'GLACE',
  'ROI', 'REINE', 'ESPION', 'SOLDAT', 'PIRATE', 'FANTÔME', 'ROBOT', 'DOCTEUR', 'JUGE', 'CLOWN',
  'ÉPÉE', 'BOUCLIER', 'CANON', 'FLÈCHE', 'BOMBE', 'MASQUE', 'COURONNE', 'ANNEAU', 'CARTE', 'DÉ',
  'CŒUR', 'OMBRE', 'FEU', 'GLACIER', 'VENT', 'SABLE', 'PIERRE', 'OR', 'ARGENT', 'CRISTAL',
  'PIANO', 'TAMBOUR', 'GUITARE', 'OPÉRA', 'CINÉMA', 'THÉÂTRE', 'CIRQUE', 'MUSÉE', 'BIBLIOTHÈQUE', 'JARDIN',
  'RACINE', 'FEUILLE', 'ROSE', 'CHAMPIGNON', 'GRAINE', 'LASER', 'AIMANT', 'ATOME', 'PLANÈTE', 'COMÈTE',
];
